name: MOLT
favicon: null
layout_spectrum: 0.85414
typography_spectrum: 0.73507
title: Theatre Based Leadership Training Program
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed3338'
    - '#ffffff'
    - '#004a5f'
    - '#c7d6dc'
    - '#b1bbbd'
  brandStrength: 0.75
  lightness: 0.1542916763573885
  saturation: 0.7219369488302618
  rhythmicContrast: 0.3290591682307422
purpose: []
