typography_spectrum: 0.73507
color:
  brandColors:
    - '#ed3338'
    - '#ffffff'
    - '#004a5f'
    - '#c7d6dc'
    - '#b1bbbd'
  brandStrength: 0.75
  lightness: 0.1542916763573885
  saturation: 0.7219369488302618
  rhythmicContrast: 0.3290591682307422
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.44358
analytics:
  google: null
  facebook: null
  twitter: null
name: MOLT
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Theatre Based Leadership Training Program
purpose: []
